# Generated by Django 4.2.4 on 2023-11-02 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=110)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], max_length=10)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], max_length=10)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='images/')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField()),
            ],
        ),
    ]
